apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mce-catalogsource
  namespace: openshift-marketplace
spec:
  image: quay.io:443/acm-d/mce-custom-registry:2.13.0-DOWNSTREAM-2025-01-05-19-09-28
  sourceType: grpc
